from PyQt6 import QtCore, QtGui, QtWidgets
from style_login_form import *


class UiLoginForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 300)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 40, 141, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_line_edit = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_line_edit.addStretch(1)
        self.verticalLayout_line_edit.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_line_edit.setObjectName("verticalLayout")
        self.login_line_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_line_edit.setObjectName("lineEdit")
        self.verticalLayout_line_edit.addWidget(self.login_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_line_edit.setObjectName("lineEdit_2")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout_line_edit.addWidget(self.password_line_edit)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 140, 101, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_button.addStretch(1)
        self.verticalLayout_button.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_button.setObjectName("verticalLayout_2")
        self.sign_in_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sign_in_push_button.setObjectName("pushButton")
        self.verticalLayout_button.addWidget(self.sign_in_push_button)
        self.sign_up_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sign_up_push_button.setObjectName("pushButton_2")
        self.verticalLayout_button.addWidget(self.sign_up_push_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(123, 190, 261, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.error_label)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_line_edit.setPlaceholderText(_translate("Form", "Login.."))
        self.password_line_edit.setPlaceholderText(_translate("Form", "Password.."))
        self.sign_in_push_button.setText(_translate("Form", "Sign In"))
        self.sign_up_push_button.setText(_translate("Form", "Sign Up"))


class UiSignUpForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 40, 141, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_register_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.login_register_line_edit.setToolTip("")
        self.login_register_line_edit.setStatusTip("")
        self.login_register_line_edit.setWhatsThis("")
        self.login_register_line_edit.setInputMask("")
        self.login_register_line_edit.setText("")
        self.login_register_line_edit.setObjectName("login_register_line_edit")
        self.verticalLayout.addWidget(self.login_register_line_edit)
        self.email_register_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email_register_line_edit.setObjectName("email_register_line_edit")
        self.verticalLayout.addWidget(self.email_register_line_edit)
        self.phone_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phone_line_edit.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.phone_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_line_edit.setObjectName("lineEdit")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.password_line_edit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 140, 101, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sign_up_register_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sign_up_register_push_button.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.sign_up_register_push_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(45, 170, 261, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.error_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_register_line_edit.setPlaceholderText(_translate("Form", "Login.."))
        self.email_register_line_edit.setPlaceholderText(_translate("Form", "Email.."))
        self.phone_line_edit.setPlaceholderText(_translate("Form", "Phone.."))
        self.password_line_edit.setPlaceholderText(_translate("Form", "Password.."))
        self.sign_up_register_push_button.setText(_translate("Form", "Sign up"))


class Ui_musapp(object):
    def setupUi(self, musapp):
        musapp.setObjectName("musapp")
        musapp.resize(1000, 595)
        musapp.setStyleSheet("background-color: rgb(62, 79, 65);")
        self.centralwidget = QtWidgets.QWidget(musapp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(510, 20, 180, 180))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 210, 120, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 260, 540, 60))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 390, 150, 150))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 390, 150, 150))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 390, 150, 150))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 170, 41))
        self.label_4.setObjectName("label_4")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 50, 170, 540))
        self.toolBox.setStyleSheet("background-color: rgb(89, 114, 93);")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 170, 472))
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 60, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 110, 113, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 170, 472))
        self.page_2.setObjectName("page_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 20, 120, 120))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 150, 120, 120))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 280, 120, 120))
        self.pushButton_9.setObjectName("pushButton_9")
        self.toolBox.addItem(self.page_2, "")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 0, 16, 591))
        self.label_5.setStyleSheet("background-color: rgb(33, 34, 32);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        musapp.setCentralWidget(self.centralwidget)

        self.retranslateUi(musapp)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(musapp)

    def retranslateUi(self, musapp):
        _translate = QtCore.QCoreApplication.translate
        musapp.setWindowTitle(_translate("musapp", "musapp"))
        self.label.setText(_translate("musapp", "Profile Pic"))
        self.label_2.setText(_translate("musapp", "Username"))
        self.label_3.setText(_translate("musapp", "Bio:"))
        self.pushButton_2.setText(_translate("musapp", "playlist 3"))
        self.pushButton_3.setText(_translate("musapp", "playlist 2"))
        self.pushButton_4.setText(_translate("musapp", "playlist1"))
        self.label_4.setText(_translate("musapp", "musapp"))
        self.pushButton.setText(_translate("musapp", "artist 1"))
        self.pushButton_5.setText(_translate("musapp", "artist 2"))
        self.pushButton_6.setText(_translate("musapp", "artist 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("musapp", "Artists"))
        self.pushButton_7.setText(_translate("musapp", "playlist 1"))
        self.pushButton_8.setText(_translate("musapp", "playlist 2"))
        self.pushButton_9.setText(_translate("musapp", "playlist 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("musapp", "playlists"))