from PyQt6 import QtCore, QtGui, QtWidgets
from style_login_form import *


class UiLoginForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 300)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 40, 141, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_line_edit = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_line_edit.addStretch(1)
        self.verticalLayout_line_edit.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_line_edit.setObjectName("verticalLayout")
        self.login_line_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.login_line_edit.setObjectName("lineEdit")
        self.verticalLayout_line_edit.addWidget(self.login_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_line_edit.setObjectName("lineEdit_2")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout_line_edit.addWidget(self.password_line_edit)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 140, 101, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_button.addStretch(1)
        self.verticalLayout_button.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_button.setObjectName("verticalLayout_2")
        self.sign_in_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sign_in_push_button.setObjectName("pushButton")
        self.verticalLayout_button.addWidget(self.sign_in_push_button)
        self.sign_up_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sign_up_push_button.setObjectName("pushButton_2")
        self.verticalLayout_button.addWidget(self.sign_up_push_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(123, 190, 261, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.error_label)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_line_edit.setPlaceholderText(_translate("Form", "Login.."))
        self.password_line_edit.setPlaceholderText(_translate("Form", "Password.."))
        self.sign_in_push_button.setText(_translate("Form", "Sign In"))
        self.sign_up_push_button.setText(_translate("Form", "Sign Up"))


class UiSignUpForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 40, 141, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_register_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.login_register_line_edit.setToolTip("")
        self.login_register_line_edit.setStatusTip("")
        self.login_register_line_edit.setWhatsThis("")
        self.login_register_line_edit.setInputMask("")
        self.login_register_line_edit.setText("")
        self.login_register_line_edit.setObjectName("login_register_line_edit")
        self.verticalLayout.addWidget(self.login_register_line_edit)
        self.email_register_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.email_register_line_edit.setObjectName("email_register_line_edit")
        self.verticalLayout.addWidget(self.email_register_line_edit)
        self.phone_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phone_line_edit.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.phone_line_edit)
        self.password_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password_line_edit.setObjectName("lineEdit")
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.verticalLayout.addWidget(self.password_line_edit)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 140, 101, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sign_up_register_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sign_up_register_push_button.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.sign_up_register_push_button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(45, 170, 261, 21))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.error_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_register_line_edit.setPlaceholderText(_translate("Form", "Login.."))
        self.email_register_line_edit.setPlaceholderText(_translate("Form", "Email.."))
        self.phone_line_edit.setPlaceholderText(_translate("Form", "Phone.."))
        self.password_line_edit.setPlaceholderText(_translate("Form", "Password.."))
        self.sign_up_register_push_button.setText(_translate("Form", "Sign up"))


class UiUserProfile(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1009, 590)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(62, 79, 65);")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(350, 370, 504, 152))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_playlist = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_playlist.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_playlist.setSpacing(26)
        self.horizontalLayout_playlist.setObjectName("horizontalLayout_playlist")
        self.playlist1_into_main = QtWidgets.QPushButton(self.layoutWidget)
        self.playlist1_into_main.setMinimumSize(QtCore.QSize(150, 150))
        self.playlist1_into_main.setMaximumSize(QtCore.QSize(150, 150))
        self.playlist1_into_main.setStyleSheet("border: 1px solid black; border-radius: 7%;"
                                               "background-color: rgb(89, 114, 93);")
        self.playlist1_into_main.setObjectName("playlist1_into_main")
        self.horizontalLayout_playlist.addWidget(self.playlist1_into_main)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 10, 591))
        self.label_5.setStyleSheet("background-color: rgb(33, 34, 32);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 181, 591))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_sidebar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.label_musapp = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_musapp.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_musapp.setObjectName("label_musapp")
        self.verticalLayout_sidebar.addWidget(self.label_musapp)
        self.toolBox = QtWidgets.QToolBox(self.layoutWidget_2)
        self.toolBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.toolBox.setStyleSheet("background-color: rgb(89, 114, 93);")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 179, 516))
        self.page.setObjectName("page")
        self.artist1_in_scroll = QtWidgets.QPushButton(self.page)
        self.artist1_in_scroll.setGeometry(QtCore.QRect(30, 10, 113, 32))
        self.artist1_in_scroll.setObjectName("artist1_in_scroll")
        self.artist2_in_scroll = QtWidgets.QPushButton(self.page)
        self.artist2_in_scroll.setGeometry(QtCore.QRect(30, 60, 113, 32))
        self.artist2_in_scroll.setObjectName("artist2_in_scroll")
        self.artist3_in_scroll = QtWidgets.QPushButton(self.page)
        self.artist3_in_scroll.setGeometry(QtCore.QRect(30, 110, 113, 32))
        self.artist3_in_scroll.setObjectName("artist3_in_scroll")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 179, 516))
        self.page_2.setObjectName("page_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, -10, 181, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 179, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_in_scroll = QtWidgets.QVBoxLayout()
        self.verticalLayout_in_scroll.setObjectName("verticalLayout_in_scroll")
        self.playlist1_into_scroll = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playlist1_into_scroll.setMinimumSize(QtCore.QSize(150, 150))
        self.playlist1_into_scroll.setMaximumSize(QtCore.QSize(150, 150))
        self.playlist1_into_scroll.setObjectName("playlist1_into_scroll")
        self.playlist1_into_scroll.setStyleSheet("border: 1px solid black; border-radius: 7%;"
                                                 "background-color: rgb(62, 79, 65);")
        self.verticalLayout_in_scroll.addWidget(self.playlist1_into_scroll)
        self.verticalLayout_4.addLayout(self.verticalLayout_in_scroll)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_sidebar.addWidget(self.toolBox)
        self.username = QtWidgets.QLabel(Form)
        self.username.setGeometry(QtCore.QRect(470, 250, 250, 51))
        self.username.setMinimumSize(QtCore.QSize(250, 0))
        self.username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username.setObjectName("username")
        self.Profile_picture = QtWidgets.QLabel(Form)
        self.Profile_picture.setEnabled(True)
        self.Profile_picture.setGeometry(QtCore.QRect(510, 40, 180, 181))
        self.Profile_picture.setMinimumSize(QtCore.QSize(180, 180))
        self.Profile_picture.setStyleSheet("border: 1px solid black; border-radius: 3%;")
        self.Profile_picture.setObjectName("Profile_picture")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 530, 31, 31))
        self.pushButton.setStyleSheet("border: 1.5px solid black; border-radius: 15%;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/plus-alt-svgrepo-com.svg"))
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.playlist1_into_main.setText(_translate("Form", "playlist1"))
        self.label_musapp.setText(_translate("Form", "musapp"))
        self.artist1_in_scroll.setText(_translate("Form", "artist 1"))
        self.artist2_in_scroll.setText(_translate("Form", "artist 2"))
        self.artist3_in_scroll.setText(_translate("Form", "artist 3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "Artists"))
        self.playlist1_into_scroll.setText(_translate("Form", "playlist 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Form", "playlists"))
        self.username.setText(_translate("Form", "Username"))
        self.Profile_picture.setText(_translate("Form", "Profile Pic"))
        # self.pushButton.setText(_translate("Form", "+"))


class UiCreatePlaylist(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton_Create = QtWidgets.QPushButton(Dialog)
        self.pushButton_Create.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.pushButton_Create.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(130, 100, 135, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet(main_style_line_edit)
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.error_label.setStyleSheet("color: rgb(202, 0, 0);")
        self.verticalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.error_label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Create.setText(_translate("Dialog", "Create"))
        self.label.setText(_translate("Dialog", "Playlist name:"))


class UiAddTrack(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.add.setObjectName("add")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 70, 135, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Track_name = QtWidgets.QLabel(self.layoutWidget)
        self.Track_name.setObjectName("Track_name")
        self.verticalLayout.addWidget(self.Track_name)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(130, 120, 135, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Executor = QtWidgets.QLabel(self.layoutWidget_2)
        self.Executor.setObjectName("Executor")
        self.verticalLayout_2.addWidget(self.Executor)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.upload_track = QtWidgets.QPushButton(Dialog)
        self.upload_track.setGeometry(QtCore.QRect(150, 180, 31, 31))
        self.upload_track.setStyleSheet("border: none;")
        self.upload_track.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/upload-icon.svg"))
        self.upload_track.setIcon(icon)
        self.upload_track.setIconSize(QtCore.QSize(24, 24))
        self.upload_track.setObjectName("upload_track")
        self.upload_cover_photo = QtWidgets.QPushButton(Dialog)
        self.upload_cover_photo.setGeometry(QtCore.QRect(210, 180, 31, 31))
        self.upload_cover_photo.setStyleSheet("border: none;")
        self.upload_cover_photo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/down_img.svg"))
        self.upload_cover_photo.setIcon(icon1)
        self.upload_cover_photo.setIconSize(QtCore.QSize(24, 24))
        self.upload_cover_photo.setObjectName("upload_cover_photo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add.setText(_translate("Dialog", "Add"))
        self.Track_name.setText(_translate("Dialog", "Track name:"))
        self.Executor.setText(_translate("Dialog", "Executor:"))


class UiAddCoowner(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(374, 300)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.add.setObjectName("add")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 70, 131, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Track_name = QtWidgets.QLabel(self.layoutWidget)
        self.Track_name.setObjectName("Track_name")
        self.verticalLayout.addWidget(self.Track_name)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setMinimumSize(0, 18)
        self.verticalLayout.addWidget(self.lineEdit)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(120, 130, 161, 101))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 99))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.coowner_1_name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.coowner_1_name.setObjectName("coowner_1_name")
        self.horizontalLayout.addWidget(self.coowner_1_name)
        self.delete_coowner_button_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_coowner_button_1.setMinimumSize(QtCore.QSize(24, 24))
        self.delete_coowner_button_1.setMaximumSize(QtCore.QSize(24, 24))
        self.delete_coowner_button_1.setStyleSheet("border:none;")
        self.delete_coowner_button_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/delete-svgrepo-com.svg"))
        self.delete_coowner_button_1.setIcon(icon)
        self.delete_coowner_button_1.setIconSize(QtCore.QSize(24, 24))
        self.delete_coowner_button_1.setObjectName("delete_coowner_button_1")
        self.horizontalLayout.addWidget(self.delete_coowner_button_1)
        self.error_label = QtWidgets.QLabel(self.layoutWidget)
        self.error_label.setText("")
        self.error_label.setObjectName("label")
        self.error_label.setStyleSheet("color: rgb(202, 0, 0);")
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.error_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add.setText(_translate("Dialog", "Add"))
        self.Track_name.setText(_translate("Dialog", "Username:"))
        self.coowner_1_name.setText(_translate("Dialog", "root_2"))


class UiPlaylistView(object):
    def setupUi(self, musapp):
        musapp.setObjectName("musapp")
        musapp.resize(1009, 590)
        musapp.setStyleSheet("background-color: rgb(62, 79, 65);")
        self.centralwidget = QtWidgets.QWidget(musapp)
        self.centralwidget.setObjectName("centralwidget")
        self.playlist_image = QtWidgets.QLabel(self.centralwidget)
        self.playlist_image.setGeometry(QtCore.QRect(560, 40, 71, 71))
        self.playlist_image.setObjectName("playlist_image")
        self.playlist_name = QtWidgets.QLabel(self.centralwidget)
        self.playlist_name.setGeometry(QtCore.QRect(500, 130, 181, 21))
        self.playlist_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.playlist_name.setObjectName("playlist_name")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(310, 250, 571, 271))
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 571, 271))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.playButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playButton_1.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_1.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_1.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_1.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play-icon.svg"))
        self.playButton_1.setIcon(icon)
        self.playButton_1.setIconSize(QtCore.QSize(12, 12))
        self.playButton_1.setCheckable(False)
        self.playButton_1.setFlat(False)
        self.playButton_1.setObjectName("playButton_1")
        self.horizontalLayout_4.addWidget(self.playButton_1)


        self.track1_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track1_image.setMaximumSize(QtCore.QSize(0, 30))
        self.track1_image.setMaximumSize(QtCore.QSize(30, 30))
        self.track1_image.setPixmap(QtGui.QPixmap("Tracks/Covers/defaulf.png"))
        self.track1_image.setScaledContents(True)
        self.track1_image.setObjectName("track1_image")


        self.horizontalLayout_4.addWidget(self.track1_image)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TrackName1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrackName1.setMinimumSize(QtCore.QSize(0, 15))
        self.TrackName1.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        # font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName1.setFont(font)
        self.TrackName1.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName1.setObjectName("TrackName1")
        self.verticalLayout_5.addWidget(self.TrackName1)
        self.ArtistName1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ArtistName1.setMinimumSize(QtCore.QSize(0, 15))
        self.ArtistName1.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName1.setFont(font)
        self.ArtistName1.setStyleSheet(" color: rgb(152, 152, 152);")
        self.ArtistName1.setObjectName("ArtistName1")
        self.verticalLayout_5.addWidget(self.ArtistName1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.add_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.add_label1.setMinimumSize(QtCore.QSize(0, 31))
        self.add_label1.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.add_label1.setFont(font)
        self.add_label1.setStyleSheet("")
        self.add_label1.setObjectName("add_label1")
        self.horizontalLayout_4.addWidget(self.add_label1)
        self.track_time1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track_time1.setMinimumSize(QtCore.QSize(0, 31))
        self.track_time1.setMaximumSize(QtCore.QSize(51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.track_time1.setFont(font)
        self.track_time1.setStyleSheet("")
        self.track_time1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_time1.setObjectName("track_time1")
        self.horizontalLayout_4.addWidget(self.track_time1)
        self.delete_button1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_button1.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_button1.setMaximumSize(QtCore.QSize(31, 16777215))
        self.delete_button1.setStyleSheet("")
        self.delete_button1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/delete-svgrepo-com.svg"))
        self.delete_button1.setIcon(icon1)
        self.delete_button1.setIconSize(QtCore.QSize(24, 24))
        self.delete_button1.setObjectName("delete_button1")
        self.horizontalLayout_4.addWidget(self.delete_button1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playButton_8.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_8.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_8.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_8.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_8.setText("")
        self.playButton_8.setIcon(icon)
        self.playButton_8.setIconSize(QtCore.QSize(12, 12))
        self.playButton_8.setObjectName("playButton_8")
        self.horizontalLayout_2.addWidget(self.playButton_8)

        self.track2_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track2_image.setMinimumSize(QtCore.QSize(0, 30))
        self.track2_image.setMaximumSize(QtCore.QSize(30, 30))
        self.track2_image.setPixmap(QtGui.QPixmap("Tracks/Covers/defaulf.png"))
        self.track2_image.setScaledContents(True)
        self.track2_image.setObjectName("track2_image")

        self.horizontalLayout_2.addWidget(self.track2_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TrackName2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrackName2.setMinimumSize(QtCore.QSize(0, 15))
        self.TrackName2.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName2.setFont(font)
        self.TrackName2.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName2.setObjectName("TrackName2")
        self.verticalLayout.addWidget(self.TrackName2)
        self.ArtistName2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ArtistName2.setMinimumSize(QtCore.QSize(0, 15))
        self.ArtistName2.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName2.setFont(font)
        self.ArtistName2.setStyleSheet("color: rgb(152, 152, 152);")
        self.ArtistName2.setObjectName("ArtistName2")
        self.verticalLayout.addWidget(self.ArtistName2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.add_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.add_label2.setMinimumSize(QtCore.QSize(0, 31))
        self.add_label2.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.add_label2.setFont(font)
        self.add_label2.setStyleSheet("")
        self.add_label2.setObjectName("add_label2")
        self.horizontalLayout_2.addWidget(self.add_label2)
        self.track_time2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track_time2.setMinimumSize(QtCore.QSize(0, 31))
        self.track_time2.setMaximumSize(QtCore.QSize(51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.track_time2.setFont(font)
        self.track_time2.setStyleSheet("")
        self.track_time2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_time2.setObjectName("track_time2")
        self.horizontalLayout_2.addWidget(self.track_time2)
        self.delete_button2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_button2.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_button2.setMaximumSize(QtCore.QSize(31, 16777215))
        self.delete_button2.setStyleSheet("")
        self.delete_button2.setText("")
        self.delete_button2.setIcon(icon1)
        self.delete_button2.setIconSize(QtCore.QSize(24, 24))
        self.delete_button2.setObjectName("delete_button2")
        self.horizontalLayout_2.addWidget(self.delete_button2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.playButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playButton_9.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_9.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_9.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_9.setText("")
        self.playButton_9.setIcon(icon)
        self.playButton_9.setIconSize(QtCore.QSize(12, 12))
        self.playButton_9.setObjectName("playButton_9")
        self.horizontalLayout_6.addWidget(self.playButton_9)
        self.track3_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track3_image.setMinimumSize(QtCore.QSize(0, 30))
        self.track3_image.setMaximumSize(QtCore.QSize(30, 30))
        self.track3_image.setPixmap(QtGui.QPixmap("Tracks/Covers/defaulf.png"))
        self.track3_image.setScaledContents(True)
        self.track3_image.setObjectName("track3_image")
        self.horizontalLayout_6.addWidget(self.track3_image)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.TrackName3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrackName3.setMinimumSize(QtCore.QSize(0, 15))
        self.TrackName3.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName3.setFont(font)
        self.TrackName3.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName3.setObjectName("TrackName3")
        self.verticalLayout_7.addWidget(self.TrackName3)
        self.ArtistName3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ArtistName3.setMinimumSize(QtCore.QSize(0, 15))
        self.ArtistName3.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName3.setFont(font)
        self.ArtistName3.setStyleSheet("color: rgb(152, 152, 152);")
        self.ArtistName3.setObjectName("ArtistName3")
        self.verticalLayout_7.addWidget(self.ArtistName3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.add_label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.add_label3.setMinimumSize(QtCore.QSize(0, 31))
        self.add_label3.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.add_label3.setFont(font)
        self.add_label3.setStyleSheet("")
        self.add_label3.setObjectName("add_label3")
        self.horizontalLayout_6.addWidget(self.add_label3)
        self.track_time3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track_time3.setMinimumSize(QtCore.QSize(0, 31))
        self.track_time3.setMaximumSize(QtCore.QSize(51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.track_time3.setFont(font)
        self.track_time3.setStyleSheet("")
        self.track_time3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_time3.setObjectName("track_time3")
        self.horizontalLayout_6.addWidget(self.track_time3)
        self.delete_button3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_button3.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_button3.setMaximumSize(QtCore.QSize(31, 16777215))
        self.delete_button3.setStyleSheet("")
        self.delete_button3.setText("")
        self.delete_button3.setIcon(icon1)
        self.delete_button3.setIconSize(QtCore.QSize(24, 24))
        self.delete_button3.setObjectName("delete_button3")
        self.horizontalLayout_6.addWidget(self.delete_button3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playButton_10.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_10.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_10.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_10.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_10.setText("")
        self.playButton_10.setIcon(icon)
        self.playButton_10.setIconSize(QtCore.QSize(12, 12))
        self.playButton_10.setObjectName("playButton_10")
        self.horizontalLayout_3.addWidget(self.playButton_10)
        self.track4_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track4_image.setMinimumSize(QtCore.QSize(0, 30))
        self.track4_image.setMaximumSize(QtCore.QSize(30, 30))
        self.track4_image.setPixmap(QtGui.QPixmap("Tracks/Covers/defaulf.png"))
        self.track4_image.setScaledContents(True)
        self.track4_image.setObjectName("track4_image")
        self.horizontalLayout_3.addWidget(self.track4_image)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TrackName4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrackName4.setMinimumSize(QtCore.QSize(0, 15))
        self.TrackName4.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName4.setFont(font)
        self.TrackName4.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName4.setObjectName("TrackName4")
        self.verticalLayout_4.addWidget(self.TrackName4)
        self.ArtistName4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ArtistName4.setMinimumSize(QtCore.QSize(0, 15))
        self.ArtistName4.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName4.setFont(font)
        self.ArtistName4.setStyleSheet("color: rgb(152, 152, 152);")
        self.ArtistName4.setObjectName("ArtistName4")
        self.verticalLayout_4.addWidget(self.ArtistName4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.add_label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.add_label4.setMinimumSize(QtCore.QSize(0, 31))
        self.add_label4.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.add_label4.setFont(font)
        self.add_label4.setStyleSheet("")
        self.add_label4.setObjectName("add_label4")
        self.horizontalLayout_3.addWidget(self.add_label4)
        self.track_time4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track_time4.setMinimumSize(QtCore.QSize(0, 31))
        self.track_time4.setMaximumSize(QtCore.QSize(51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.track_time4.setFont(font)
        self.track_time4.setStyleSheet("")
        self.track_time4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_time4.setObjectName("track_time4")
        self.horizontalLayout_3.addWidget(self.track_time4)
        self.delete_button4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_button4.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_button4.setMaximumSize(QtCore.QSize(31, 16777215))
        self.delete_button4.setStyleSheet("")
        self.delete_button4.setText("")
        self.delete_button4.setIcon(icon1)
        self.delete_button4.setIconSize(QtCore.QSize(24, 24))
        self.delete_button4.setObjectName("delete_button4")
        self.horizontalLayout_3.addWidget(self.delete_button4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.playButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.playButton_11.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_11.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_11.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_11.setText("")
        self.playButton_11.setIcon(icon)
        self.playButton_11.setIconSize(QtCore.QSize(12, 12))
        self.playButton_11.setObjectName("playButton_11")
        self.horizontalLayout_5.addWidget(self.playButton_11)
        self.track5_image = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track5_image.setMinimumSize(QtCore.QSize(0, 30))
        self.track5_image.setMaximumSize(QtCore.QSize(30, 30))
        self.track5_image.setPixmap(QtGui.QPixmap("Tracks/Covers/defaulf.png"))
        self.track5_image.setScaledContents(True)
        self.track5_image.setObjectName("track5_image")
        self.horizontalLayout_5.addWidget(self.track5_image)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TrackName5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.TrackName5.setMinimumSize(QtCore.QSize(0, 15))
        self.TrackName5.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName5.setFont(font)
        self.TrackName5.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName5.setObjectName("TrackName5")
        self.verticalLayout_6.addWidget(self.TrackName5)
        self.ArtistName5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ArtistName5.setMinimumSize(QtCore.QSize(0, 15))
        self.ArtistName5.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName5.setFont(font)
        self.ArtistName5.setStyleSheet("color: rgb(152, 152, 152);")
        self.ArtistName5.setObjectName("ArtistName5")
        self.verticalLayout_6.addWidget(self.ArtistName5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.add_label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.add_label5.setMinimumSize(QtCore.QSize(0, 31))
        self.add_label5.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.add_label5.setFont(font)
        self.add_label5.setStyleSheet("")
        self.add_label5.setObjectName("add_label5")
        self.horizontalLayout_5.addWidget(self.add_label5)
        self.track_time5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.track_time5.setMinimumSize(QtCore.QSize(0, 31))
        self.track_time5.setMaximumSize(QtCore.QSize(51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.track_time5.setFont(font)
        self.track_time5.setStyleSheet("")
        self.track_time5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_time5.setObjectName("track_time5")
        self.horizontalLayout_5.addWidget(self.track_time5)
        self.delete_button5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_button5.setMinimumSize(QtCore.QSize(31, 31))
        self.delete_button5.setMaximumSize(QtCore.QSize(31, 16777215))
        self.delete_button5.setStyleSheet("")
        self.delete_button5.setText("")
        self.delete_button5.setIcon(icon1)
        self.delete_button5.setIconSize(QtCore.QSize(24, 24))
        self.delete_button5.setObjectName("delete_button5")
        self.horizontalLayout_5.addWidget(self.delete_button5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(180, 0, 10, 591))
        self.label_13.setStyleSheet("background-color: rgb(33, 34, 32);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 0, 181, 591))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_sidebar.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.label_musapp = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_musapp.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_musapp.setObjectName("label_musapp")
        self.verticalLayout_sidebar.addWidget(self.label_musapp)
        self.toolBox_2 = QtWidgets.QToolBox(self.layoutWidget_5)
        self.toolBox_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.toolBox_2.setStyleSheet("background-color: rgb(89, 114, 93);")
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 179, 516))
        self.page_3.setObjectName("page_3")
        self.artist1_in_scroll = QtWidgets.QPushButton(self.page_3)
        self.artist1_in_scroll.setGeometry(QtCore.QRect(30, 10, 113, 32))
        self.artist1_in_scroll.setObjectName("artist1_in_scroll")
        self.artist2_in_scroll = QtWidgets.QPushButton(self.page_3)
        self.artist2_in_scroll.setGeometry(QtCore.QRect(30, 60, 113, 32))
        self.artist2_in_scroll.setObjectName("artist2_in_scroll")
        self.artist3_in_scroll = QtWidgets.QPushButton(self.page_3)
        self.artist3_in_scroll.setGeometry(QtCore.QRect(30, 110, 113, 32))
        self.artist3_in_scroll.setObjectName("artist3_in_scroll")
        self.toolBox_2.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 179, 516))
        self.page_4.setObjectName("page_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, -10, 181, 531))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 179, 529))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_in_scroll = QtWidgets.QVBoxLayout()
        self.verticalLayout_in_scroll.setObjectName("verticalLayout_in_scroll")
        self.playlist1_into_scroll = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.playlist1_into_scroll.setMinimumSize(QtCore.QSize(150, 150))
        self.playlist1_into_scroll.setObjectName("playlist1_into_scroll")
        self.verticalLayout_in_scroll.addWidget(self.playlist1_into_scroll)
        self.verticalLayout_8.addLayout(self.verticalLayout_in_scroll)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.toolBox_2.addItem(self.page_4, "")
        self.verticalLayout_sidebar.addWidget(self.toolBox_2)
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(200, 30, 24, 24))
        self.back_button.setMinimumSize(QtCore.QSize(24, 24))
        self.back_button.setMaximumSize(QtCore.QSize(24, 24))
        self.back_button.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.back_button.setStyleSheet("border: none;")
        self.back_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/back-icons.svg"))
        self.back_button.setIcon(icon2)
        self.back_button.setIconSize(QtCore.QSize(24, 24))
        self.back_button.setCheckable(False)
        self.back_button.setFlat(False)
        self.back_button.setObjectName("back_button")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(510, 230, 161, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.coowner_button = QtWidgets.QPushButton(self.widget)
        self.coowner_button.setMinimumSize(QtCore.QSize(31, 31))
        self.coowner_button.setMaximumSize(QtCore.QSize(31, 16777215))
        self.coowner_button.setStyleSheet("border: 1.5px solid black; border-radius: 15%;")
        self.coowner_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/coowner-icon.svg"))
        self.coowner_button.setIcon(icon2)
        self.coowner_button.setObjectName("coowner_button")
        self.horizontalLayout.addWidget(self.coowner_button)
        self.playlist_delete_button = QtWidgets.QPushButton(self.widget)
        self.playlist_delete_button.setMinimumSize(QtCore.QSize(31, 31))
        self.playlist_delete_button.setMaximumSize(QtCore.QSize(31, 16777215))
        self.playlist_delete_button.setStyleSheet("border: 1.5px solid black; border-radius: 15%;")
        self.playlist_delete_button.setText("")
        self.playlist_delete_button.setIcon(icon1)
        self.playlist_delete_button.setIconSize(QtCore.QSize(24, 24))
        self.playlist_delete_button.setObjectName("playlist_delete_button")
        self.horizontalLayout.addWidget(self.playlist_delete_button)
        self.add_track_button = QtWidgets.QPushButton(self.widget)
        self.add_track_button.setMinimumSize(QtCore.QSize(31, 31))
        self.add_track_button.setMaximumSize(QtCore.QSize(31, 16777215))
        self.add_track_button.setStyleSheet("border: 1.5px solid black; border-radius: 15%;")
        self.add_track_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/plus-alt-svgrepo-com.svg"))
        self.add_track_button.setIcon(icon3)
        self.add_track_button.setIconSize(QtCore.QSize(24, 24))
        self.add_track_button.setObjectName("add_track_button")
        self.horizontalLayout.addWidget(self.add_track_button)

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 520, 561, 71))
        self.widget.setObjectName("widget")
        self.playing_track_verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.playing_track_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.playing_track_verticalLayout.setSpacing(0)
        self.playing_track_verticalLayout.setObjectName("playing_track_verticalLayout")
        self.track_time_slider_down = QtWidgets.QSlider(self.widget)
        self.track_time_slider_down.setStyleSheet(track_time_slider_style)
        self.track_time_slider_down.setPageStep(10)
        self.track_time_slider_down.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.track_time_slider_down.setObjectName("track_time_slider_down")
        self.playing_track_verticalLayout.addWidget(self.track_time_slider_down)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.playButton_down = QtWidgets.QPushButton(self.widget)
        self.playButton_down.setMinimumSize(QtCore.QSize(24, 24))
        self.playButton_down.setMaximumSize(QtCore.QSize(24, 24))
        self.playButton_down.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton_down.setStyleSheet("border: 1.5px solid black; border-radius: 12%;")
        self.playButton_down.setText("")
        self.playButton_down.setIcon(icon)
        self.playButton_down.setIconSize(QtCore.QSize(12, 12))
        self.playButton_down.setCheckable(False)
        self.playButton_down.setFlat(False)
        self.playButton_down.setObjectName("playButton_down")
        self.horizontalLayout_7.addWidget(self.playButton_down)
        self.skip_button_down = QtWidgets.QPushButton(self.widget)
        self.skip_button_down.setMinimumSize(QtCore.QSize(24, 24))
        self.skip_button_down.setMaximumSize(QtCore.QSize(24, 24))
        self.skip_button_down.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.skip_button_down.setStyleSheet("border:none;")
        self.skip_button_down.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/skip-forward-icon.svg"))
        self.skip_button_down.setIcon(icon5)
        self.skip_button_down.setIconSize(QtCore.QSize(24, 24))
        self.skip_button_down.setCheckable(False)
        self.skip_button_down.setFlat(False)
        self.skip_button_down.setObjectName("skip_button_down")
        self.horizontalLayout_7.addWidget(self.skip_button_down)
        self.track_image_down = QtWidgets.QLabel(self.widget)
        self.track_image_down.setMinimumSize(QtCore.QSize(40, 40))
        self.track_image_down.setMaximumSize(QtCore.QSize(40, 40))
        self.track_image_down.setStyleSheet(
            "border: 1px solid black; border-radius: 8px;  background-image: url(\"C:/Users/stade/Downloads/sunset-4475686_1920.jpg\"); background-position: center;")
        self.track_image_down.setText("")
        self.track_image_down.setScaledContents(True)
        self.track_image_down.setObjectName("track_image_down")
        self.horizontalLayout_7.addWidget(self.track_image_down)
        self.verticalLayout_trackname_down = QtWidgets.QVBoxLayout()
        self.verticalLayout_trackname_down.setSpacing(0)
        self.verticalLayout_trackname_down.setObjectName("verticalLayout_trackname_down")
        self.TrackName_down = QtWidgets.QLabel(self.widget)
        self.TrackName_down.setMinimumSize(QtCore.QSize(0, 0))
        self.TrackName_down.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.TrackName_down.setFont(font)
        self.TrackName_down.setStyleSheet("color: rgb(255, 255, 255);")
        self.TrackName_down.setObjectName("TrackName_down")
        self.verticalLayout_trackname_down.addWidget(self.TrackName_down)
        self.ArtistName_down = QtWidgets.QLabel(self.widget)
        self.ArtistName_down.setMinimumSize(QtCore.QSize(0, 0))
        self.ArtistName_down.setMaximumSize(QtCore.QSize(250, 15))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.ArtistName_down.setFont(font)
        self.ArtistName_down.setStyleSheet(" color: rgb(152, 152, 152);")
        self.ArtistName_down.setObjectName("ArtistName_down")
        self.verticalLayout_trackname_down.addWidget(self.ArtistName_down)
        self.horizontalLayout_7.addLayout(self.verticalLayout_trackname_down)
        self.volume_icon_down = QtWidgets.QPushButton(self.widget)
        self.volume_icon_down.setMinimumSize(QtCore.QSize(31, 31))
        self.volume_icon_down.setMaximumSize(QtCore.QSize(31, 31))
        self.volume_icon_down.setStyleSheet("border: none;")
        self.volume_icon_down.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/high-volume-icon.svg"))
        self.volume_icon_down.setIcon(icon6)
        self.volume_icon_down.setIconSize(QtCore.QSize(24, 24))
        self.volume_icon_down.setObjectName("volume_icon_down")
        self.horizontalLayout_7.addWidget(self.volume_icon_down)
        self.volume_slider_down = QtWidgets.QSlider(self.widget)
        self.volume_slider_down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.volume_slider_down.setStyleSheet(volume_slider_style)
        self.volume_slider_down.setMaximum(100)
        self.volume_slider_down.setProperty("value", 100)
        self.volume_slider_down.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider_down.setObjectName("volume_slider_down")
        self.horizontalLayout_7.addWidget(self.volume_slider_down)
        self.playing_track_verticalLayout.addLayout(self.horizontalLayout_7)
        musapp.setCentralWidget(self.centralwidget)

        self.retranslateUi(musapp)
        self.toolBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(musapp)

    def retranslateUi(self, musapp):
        _translate = QtCore.QCoreApplication.translate
        musapp.setWindowTitle(_translate("musapp", "musapp"))

        self.playlist_name.setText(_translate("musapp", "playlistName"))
        # self.track1_image.setText(_translate("musapp", "TextLabel"))
        self.TrackName1.setText(_translate("musapp", "TrackName"))
        self.ArtistName1.setText(_translate("musapp", "ArtistName"))
        self.add_label1.setText(_translate("musapp", "add: owner"))
        self.track_time1.setText(_translate("musapp", "03:47"))

        self.TrackName2.setText(_translate("musapp", "TrackName"))
        self.ArtistName2.setText(_translate("musapp", "ArtistName"))
        self.add_label2.setText(_translate("musapp", "add: owner"))
        self.track_time2.setText(_translate("musapp", "03:47"))

        self.TrackName3.setText(_translate("musapp", "TrackName"))
        self.ArtistName3.setText(_translate("musapp", "ArtistName"))
        self.add_label3.setText(_translate("musapp", "add: owner"))
        self.track_time3.setText(_translate("musapp", "03:47"))

        self.TrackName4.setText(_translate("musapp", "TrackName"))
        self.ArtistName4.setText(_translate("musapp", "ArtistName"))
        self.add_label4.setText(_translate("musapp", "add: owner"))
        self.track_time4.setText(_translate("musapp", "03:47"))

        self.TrackName5.setText(_translate("musapp", "TrackName"))
        self.ArtistName5.setText(_translate("musapp", "ArtistName"))
        self.add_label5.setText(_translate("musapp", "add: owner"))
        self.track_time5.setText(_translate("musapp", "03:47"))
        self.label_musapp.setText(_translate("musapp", "musapp"))
        self.artist1_in_scroll.setText(_translate("musapp", "artist 1"))
        self.artist2_in_scroll.setText(_translate("musapp", "artist 2"))
        self.artist3_in_scroll.setText(_translate("musapp", "artist 3"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), _translate("musapp", "Artists"))
        self.playlist1_into_scroll.setText(_translate("musapp", "playlist 1"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("musapp", "playlists"))

        self.TrackName_down.setText(_translate("musapp", "TrackName"))
        self.ArtistName_down.setText(_translate("musapp", "ArtistName"))


